vim.o.expandtab = true
vim.o.tabstop = 4
vim.o.softtabstop = 4
vim.o.shiftwidth = 4
vim.g.mapleader = " "
vim.o.clipboard = "unnamedplus"
vim.wo.number = true
vim.wo.relativenumber = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.opt.termguicolors = true
vim.g.neovide_scale_factor = 1.0
vim.o.guifont = "FiraCode Nerd Font:h18"
